WARNING  pytest_result_log:plugin.py:122 ------------Start: unit_tests/test_add.py::TestAdd::test_ddt[4-4-7]-------------
WARNING  pytest_result_log:plugin.py:128 -------------End: unit_tests/test_add.py::TestAdd::test_ddt[4-4-7]--------------