WARNING  pytest_result_log:plugin.py:122 ------------------Start: unit_tests/test_rerun.py::test_rerun-------------------
WARNING  pytest_result_log:plugin.py:128 -------------------End: unit_tests/test_rerun.py::test_rerun--------------------